# Generated by Django 4.2.1 on 2023-05-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_uz',
        ),
    ]
